channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=20.3.3
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - pandas==1.1.4
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==0.24.1
  - scipy==1.13.0
name: mlflow-env
